# Generated by Django 4.2.9 on 2024-02-20 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(default=None, max_length=250, null=True, upload_to='orderservices/'),
        ),
    ]
