# Generated by Django 4.2.9 on 2024-02-21 10:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderservice', '0002_alter_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='time_session',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
