# Generated by Django 4.2.9 on 2024-02-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderservice', '0003_orderlist_time_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='time_session',
        ),
    ]
