# Generated by Django 4.2.9 on 2024-03-22 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderservice', '0004_remove_orderlist_time_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='alluser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('total_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderservice.orderlist')),
            ],
        ),
    ]
